const MAX_RESULTS=16;
const FILTERS={all:{query:model=>`${model} фото техники`},manufacturer:{query:model=>`${model} официальный сайт фото`},stores:{query:model=>`${model} купить фото`},media:{query:model=>`${model} обзор фото`}};
function clean(value,max){return String(value||'').replace(/\s+/g,' ').trim().slice(0,max)}
function httpUrl(value){try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)?url.href:null}catch{return null}}
function domain(value){try{return new URL(value).hostname.replace(/^www\./,'')}catch{return 'Источник'}}
function decodeXml(value){return String(value||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#(?:x([\da-f]+)|(\d+));/gi,(_,hex,decimal)=>String.fromCodePoint(parseInt(hex||decimal,hex?16:10))).replace(/&amp;/g,'&')}
function xmlTag(xml,tag){const match=String(xml).match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)</${tag}>`,'i'));return match?decodeXml(match[1].replace(/<[^>]*>/g,' ')):''}
function yandexImageSearchUrl(query){return `https://yandex.ru/images/search?text=${encodeURIComponent(query)}`}
async function searchGoogle(query){if(!process.env.SERPER_API_KEY)throw new Error('Google Images не настроен: добавь SERPER_API_KEY в Vercel.');const response=await fetch('https://google.serper.dev/images',{method:'POST',headers:{'X-API-KEY':process.env.SERPER_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({q:query,num:MAX_RESULTS,gl:'ru',hl:'ru',autocorrect:false})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.message||payload?.error||'Google Images не ответил.');const seen=new Set();return (Array.isArray(payload.images)?payload.images:[]).map(item=>{const imageUrl=httpUrl(item.imageUrl||item.thumbnailUrl);const pageUrl=httpUrl(item.link||item.source||item.imageUrl);if(!imageUrl||!pageUrl||seen.has(imageUrl))return null;seen.add(imageUrl);return {imageUrl,pageUrl,title:clean(item.title,180)||query,domain:domain(pageUrl),engine:'google'}}).filter(Boolean)}
function parseYandexImages(rawData,query){const xml=Buffer.from(String(rawData||''),'base64').toString('utf8');const blocks=xml.match(/<doc(?:\s[^>]*)?>[\s\S]*?<\/doc>/gi)||[];const seen=new Set();return blocks.map(block=>{const imageUrl=httpUrl(xmlTag(block,'url')||xmlTag(block,'original-url')||xmlTag(block,'img-url'));if(!imageUrl||seen.has(imageUrl))return null;seen.add(imageUrl);const sourceDomain=clean(xmlTag(block,'domain'),140)||domain(imageUrl);const title=clean(xmlTag(block,'title'),180)||query;return {imageUrl,pageUrl:yandexImageSearchUrl(query),title,domain:sourceDomain,engine:'yandex'}}).filter(Boolean)}
async function searchYandex(query){if(!process.env.YANDEX_SEARCH_API_KEY||!process.env.YANDEX_FOLDER_ID)throw new Error('Яндекс Картинки не настроен: добавь YANDEX_SEARCH_API_KEY и YANDEX_FOLDER_ID в Vercel.');const response=await fetch('https://searchapi.api.cloud.yandex.net/v2/image/search',{method:'POST',headers:{'Authorization':`Api-Key ${process.env.YANDEX_SEARCH_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({query:{searchType:'ru',queryText:query,familyMode:'strict',page:'0',fixTypoMode:'off'},imageSpec:{size:'LARGE'},docsOnPage:String(MAX_RESULTS),folderId:process.env.YANDEX_FOLDER_ID})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.message||payload?.error||'Яндекс Картинки не ответил.');const images=parseYandexImages(payload.rawData,query);if(!images.length)throw new Error('Яндекс Картинки не вернул пригодных для показа ссылок.');return images}
function uniqueImages(images){const seen=new Set();return images.filter(image=>{const key=image.imageUrl.toLowerCase();if(seen.has(key))return false;seen.add(key);return true}).slice(0,MAX_RESULTS)}
module.exports=async function(req,res){if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).json({error:'Используй POST.'})}try{const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const model=clean(body.model,140);const filter=FILTERS[body.filter]?body.filter:'all';const engine=['google','yandex','both'].includes(body.engine)?body.engine:'both';if(!model)return res.status(400).json({error:'Укажи модель техники.'});const query=FILTERS[filter].query(model);const searches=[];if(engine==='google'||engine==='both')searches.push({engine:'google',task:searchGoogle(query)});if(engine==='yandex'||engine==='both')searches.push({engine:'yandex',task:searchYandex(query)});const settled=await Promise.allSettled(searches.map(item=>item.task));const images=[];const errors=[];settled.forEach((result,index)=>{if(result.status==='fulfilled')images.push(...result.value);else errors.push({engine:searches[index].engine,error:result.reason?.message||'Поиск недоступен.'})});const usable=uniqueImages(images);if(!usable.length)return res.status(503).json({error:errors.map(item=>item.error).join(' ')});return res.status(200).json({model,filter,engine,images:usable,errors})}catch(error){return res.status(502).json({error:error.message||'Ошибка поиска фотографий.'})}};
module.exports.config={maxDuration:30};
